
spring:
  profiles:
    active: dev
  security:
    jwt:
      secret: ${JWT_SECRET:my-secret-key}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/api-sale-10?createDatabaseIfNotExist=true&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: unitel.12345
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        # update atualiza os schemas de banco de dados, none, validate, update, create, create-drop
        ddl-auto: update